#!/bin/bash
#Change all hound users programmatically.
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -


#TODO: Make sure that user is running from sudo and not from root when running this command.
i=1;
while read -r line
do
    #user=$(printf "$line" | cut -d':' -f1 );
    #password=$( printf "$line" | cut -d':' -f2 );
    echo "Changing password for hound$i";
    let i++;
    echo "$line" | chpasswd

done < the_flags;
