#!/bin/bash
#Change all hound users programmatically.
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019-


#TODO: Make sure that user is running from sudo and not from root when running this command.
FLAG_HOUND0='-WeE1KX.EkmECsU-xKSki7cSQb8';
FLAG_HOUND1='k3uLis-bFoOtxl8wBllZsKapwqM';
FLAG_HOUND2='X3kIeNDOe41RPMD0H7Oxt88fmlg';
FLAG_HOUND3='jEKpny.vBXBCLg5EA.D-RKZPH8w';
FLAG_HOUND4='3h9GplLdLnj9e6uYVToiNMBLFcY';
#right now it's an array of values in the future it'll read it from a text file.
hounds_pass=('hound0password','-WeE1KX.EkmECsU-xKSki7cSQb8','k3uLis-bFoOtxl8wBllZsKapwqM','X3kIeNDOe41RPMD0H7Oxt88fmlg','jEKpny.vBXBCLg5EA.D-RKZPH8w','3h9GplLdLnj9e6uYVToiNMBLFcY')
hounds=6;
for (( i=0; i -lt hounds; i++ )){
    echo 'Changing password for hound:'$i;
    chpasswd "hound$i:${hounds_pass[$i]}";
}
