#!/bin/bash
#Change all hound users programmatically.
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019-


#TODO: Make sure that user is running from sudo and not from root when running this command.
i=1;
user='';
password='';
while read line
do
    user=$(printf "$line" | cut -d':' -f1 );
    password=$( printf "$line" | cut -d':' -f2 );
    echo "Changing password for hound$i";
    let i++;
    chpasswd "$user:$password"

done < the_flags;
