#!/bin/bash
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019- AGPLv3
cd $1;
ls > /tmp/dirs;
shopt -s dotglob
while read line;
do
    cd "$line";
    pwd;
    echo "$1:";
    mkdir -p ../../"hounds_built/$line";
    chmod 777 ../../"$hounds_built/$line";
    tar -cvJf ../../"hounds_built/$line/"challenge_file.txz *;
    chmod 777 ../../"hounds_built/$line/"challenge_file.txz;
   cd ..;
done < /tmp/dirs
shopt -u dotglob
