#!/bin/bash
#This script reads from a file and then changes all user's passwords programmatically.
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
if [[ $EUID -eq 0 ]];then
    cat the_flags | chpasswd;
    echo -e 'All passwords \e[4mShould\e[0m be updated now.'
else
    printf 'This script should only be run via sudo. Do not run as root for safety reasons.';
fi
