#!/bin/bash
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019- AGPLv3

FLAG_HOUND3='jEKpny.vBXBCLg5EA.D-RKZPH8w';
filename_arr=('this file has spaces' 'name has spaces' 'space character' 'many spaces within it' 'within the filename spaces');
filename_arr_len=${#filename_arr[*]};
filename=${filename_arr[$(( $RANDOM % $filename_arr_len ))]};
dirname_arr=('.secrets' '.filthy_lucre' '.files' '.information' '.top_secret' '.hidden' '.mystery');
dirname_arr_len=${#dirname_arr[*]};
dirname=${dirname_arr[$(( $RANDOM % $dirname_arr_len ))]};

cd ../hounds/hound3;
#this is to make sure to deal with files that have spaces in their name as we're looking for certain ones
#just in case there are ones in the home directory that do have spaces in their
#names.
tmp=${dirname_arr[0]};
for (( i=1; i<$dirname_arr_len; i++ )){ 
    tmp="$tmp|${dirname_arr[$i]}";
}
#otherwise the above could would no be needed at all.
ls -a | egrep "($tmp)"| tr '|' '\n'|xargs -d'\n' rm -vdR
#'and this line; tr could be removed and it would just be a `ls | egrep "(\ )" | rm -v` that is it'.
mkdir $dirname;
cd $dirname;
#file_name=${filename_arr[$(( $RANDOM % $filename_arr_len ))]};



echo "$FLAG_HOUND3" > "$filename";
chown -R 1004 "$filename";
cd ../../../build_scripts
