#!/bin/bash
# Hound ??: Work it, let me work it. Flip it and reverse it. ti tuc ,ti rt ,ti ver ,ti qinu ,ti troS
# This hound flag will combine the following commands into one. They'll sort a file, then get the only uniq
# line. After that, reverse the string, tr it from mixed-case to lowercase. Then the flag is the second field.
# so if they use cut they can instantly get it.
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -

HASH_ENCODING='b32';
if [[ $# -lt 1 ]];then
    level=15;
else
    level=$1;
fi
source build_functions;
WORD_ARRAY=(25 5 6 7 8 26 27);
tmp_rnd=`( dd if=/dev/urandom bs=2 count=1 status=none | od -A n -t u )`;
#chosen_word=${WORD_ARRAY[$(( $RANDOM % 7 ))]};
chosen_word=${WORD_ARRAY[$(( $tmp_rnd % 7 ))]};
FLAG_HOUND=$( make_semistatic_flag $chosen_word);
