#!/bin/bash
# Hound 12 aka `A sed is fine too.`
# Macarthur Inbody <mdi2455@email.vccs.edu>
# AGPLv3
# 2019 -
# This flag will require them to take the input that's a bunch of lines of text
# then delete all lines that contain some sort of regex pattern that'll then give them their flag.
# to cause them to no be able to just _look_ at it, the file will be ~200lines long.
# The regex will be one of the following. All Uppercase, 2-6 uppercase letters, 6-9 numbers in the string.
# The start is an uppercase letter. The start is 3-4 numbers. The end contains an uppercase letter. The end
# contains 3-4 numbers in a row.
# They're going to have to either print(the correct line) or delete all lines that don't match the query.
# They'll be given information the flag file to help them along.

