#!/bin/bash
# Hound 16 aka `I'm a genius program, my script can't have syntax errors!`
# Macarthur Inbody <mdi2455@email.vccs.edu>
# AGPLv3
# 2019 -
# this flag will generate a bash script that has a couple of syntax errors.
# Basically they'll have to fix a logic error, fix a typo in a variable name.
# then they'll also have to fix a syntax error. After doing this, they'll
# then be able to get the program to generate a string for them after passing it an argument. Super simple thing to make sure they
# get some basic bash scripting.
# errors will include logic error, typoed variable, using [[]] instead of (()) for a loop, same with if/else if. Writing if else if. Doing the if/else loop with C-Style syntax etc. After fixing it up
#the program will check the argument passed to it and then process it
# and turn it into a string(using some function that won't have issues with it) by going through the string character by character transforming it someway.


WORD_ARRAY=(15 16 17 18 19 20 21);
chosen_word=${WORD_ARRAY[$(( $RANDOM & 6 ))]};
FLAG_HOUND=$( make_semistatic_flag $chosen_word);
