#!/bin/bash
#Hound 15 aka `I have a problem. I know I'll use regex. Now I have 2 problems.`
# Macarthur Inbody <mdi2455@email.vccs.edu>
# AGPLv3
# 2019 -
# This flag requires them to write a regex that will match the line that has a set of strings. They'll be
# utilizing grep or something similar to help with the input filtering for the following flag.
