#!/bin/bash
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019- AGPLv3
#the flag will be exported later so that it can be read from a file.

#this is the level that this flag is going to be identified as.
level=1;
#this reads in the functions that are in the library.
source build_functions;
#we seed $RANDOM with the current level value.
seed_random $level;
#we then make the flag by calling it.
FLAG_HOUND1=$( make_flag $level );
#we continue by selecting things semi_randomly.
#when we are in debug mode it'll be calling debug_random
continue_random;
# the old flag.
#FLAG_HOUND1='k3uLis-bFoOtxl8wBllZsKapwqM';

#The prefixes for the files
filename_arr=('.-' '-~' '-.' '.~');
filename_arr_len=${#filename_arr[*]};
#This line removes the old flag and puts the new file in there.
cd ../hounds/hound1/
tmp=$( echo ${filename_arr[*]} | tr ' ' '|' );
echo "$tmp";
rm -v './'$( ls -a | egrep "($tmp)");

file_name=${filename_arr[$(( $RANDOM % $filename_arr_len ))]};



echo "The flag is $FLAG_HOUND1" > ./$file_name;
chown 1002 ./"$file_name";
cd ../../build_scripts/
