#!/bin/bash
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019- AGPLv3
#the flag will be exported later so that it can be read from a file.
FLAG_HOUND2='X3kIeNDOe41RPMD0H7Oxt88fmlg';
filename_arr=('this file has spaces' 'name has spaces' 'space character' 'many spaces within it' 'within filename spaces');
filename_arr_len=${#filename_arr[*]};
cd ../hounds/hound2/
#this is to make sure to deal with files that have spaces in their name as we're looking for certain ones
#just in case there are ones in the home directory that do have spaces in their
#names.
tmp=${filename_arr[0]};
for (( i=1; i<$filename_arr_len; i++ )){ 
    tmp="$tmp|${filename_arr[$i]}";
}
#otherwise the above could would no be needed at all.
ls | egrep "($tmp)"| tr '|' '\n'|xargs -d'\n' rm -v
#'and this line; tr could be removed and it would just be a `ls | egrep "(\ )" | rm -v` that is it'.
file_name=${filename_arr[$(( $RANDOM % $filename_arr_len ))]};



echo "$FLAG_HOUND2" > "$file_name";
chown 1003 "$file_name";
cd ../../build_scripts
