#!/bin/bash
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -

# The hound8 flag has permissions that are not normal thus it must be done as root
# So that we can retain the correct ownership/group ownership permissions 
# that we have.
if [[ $(whoami) != "root" ]];then
	echo "Must be run as root.";
	exit 1;
fi

cd ../hounds_built;
for ((i=0;i<=17;i++ )){
    rm -v ../home_folders/"hound$i/challenge_file.txz";
    cp -v hound$i/challenge_file.txz ../home_folders/"hound$i/challenge_file.txz";
    rm -v /home/"hound$i"/challenge_file.txz;
    cp -v hound"$i"/challenge_file.txz /home/hound$i/challenge_file.txz;
}
