#!/bin/bash
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
cd ../hounds_built;
for ((i=0;i<=17;i++ )){
    cp -v hound$i/challenge_file.txz ../home_folders/"hound$i/challenge_file.txz";
}
