#!/bin/bash
#moves the c programs to the built directory along with making sure that the masks are correct.
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
cd ../c_programs
cp -aRv built /usr/local/bin;
