#!/bin/bash
read -r CURRENT_BUILD < ../notes/current_build_number;
if [[ $CURRENT_BUILD -ge 11 ]];then
    CURRENT_BUILD=0;
else
    printf '%s\n' $((CURRENT_BUILD+1)) > ../notes/current_build_number;
fi
