#!/bin/bash
# RegEx Script
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
# This script is what they're going to pass their regex to to have it
# search the file they've been told for the search string.
# If they look at it how it's doing it I've just used grep for the regex since
# it won't give them the answer for any future flags.

#you need to pass it the correct regex pattern and the file we're going to be searching.
args=$#;
case $args in
    1)
        printf "You need to submit two options. First is the regex string. Second is the file to search. Make sure both are covered in ''.\n"
        printf "Like so ./regex_searcher.sh '/SOMEREGEX/' Also file has to be properly escaped if it's needed.\n"
    ;;
    2)
        sed -n "$1 p" "$2"
    ;;
    *)
        printf "You need to submit two options. First is the regex string. Second is the file to search. Make sure both are covered in ''.\n"
        printf "Like so ./regex_searcher.sh '/SOMEREGEX/' SOMEFILE\n"
    ;;
esac
