#!/bin/bash
#The following is the smushed and ready to be echoed out "M" header with all of 
#the color information intact.
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -

#to make sure that the logos will fit on the screen at one time with the user's 
#prompt. I also went over by three characters in the columns so I have to resize it
#for that also.
#to make sure it doesn't output pointless lines.
#resize -s 27 83 &>/dev/null;

#This is included to help me easily revert it to change the textbox later.
#I have ~362 characters to work with within it. It should be way more than enough
#for pretty much everything that I'll need to do as that's 80words. I'll create
#smaller versions of the textbox for earlier flags. Small box should be ~100 chars.

#color table: 31=red fg, 33=yellow fg, 97=white fg. 1=bold,4=underlined.
word='1005'
padding=$(printf $word | wc -c);
padding=$(( 10 - $padding ));
WORD=$( printf "%s.%${padding}s" $word '' );
padding=$( printf $USER | wc -c );
padding=$(( 13 - $padding ));
user=$( printf "%s.%${padding}s" $USER '' );
#remove later.
#old colored version
#current version.
#I start off by clearing all formatting so that I can be sure that it'll show up
#the way that I want. Then I go into using escape codes to colorize it to look
#way nicer. The text at the top will likely just be MECC.edu/Cyber or something
#similar.
echo '\e[0m\e[31m                        /#\
\e[31m                       /###\
\e[31m                      /#####\
\e[31m                     /#######\
\e[31m                    /#########\           \e[1m*****\e[1;4mWelcome to the Hunt @ MECC\e[24m****\e[0m   
\e[31m                   /##########/           \e[33m+=======================================+
\e[31m                  /##########/  /\        \e[33m|\e[97m You are on currently on '"$user"'\e[33m|
\e[31m                 /##########/  /##\       \e[33m|\e[97m The goal of this level is to join the \e[33m|   
\e[31m                /##########/  /###/  _    \e[33m|\e[97m two files after sorting them properly.\e[33m|   
\e[31m               /##########/__/###/  /#\   \e[33m|\e[97mThe answer is on the line with the word\e[33m|
\e[31m              /#################/  /###\  \e[33m|\e[97m '"$WORD"'The Field Seperator is `:` \e[33m|
\e[31m             /#################/  /#####\  \e[33m\ \e[97m Some interesting commands to try    \e[33m|
\e[31m           /##################/__/#######\  \e[33m\ \e[97m ls,cat,file,join,sortman,info      \e[33m|
\e[31m          /###############################\  \e[33m\ \e[97mIf \e[1;4myou\e[0;97m mess up: reset_ctf          \e[33m|
\e[31m         /#######/\########################\  \e[33m\ \e[97mIf \e[1;4mit\e[0;97m messes up: blame -debug     \e[33m|
\e[31m        /#######/  \########################\  \e[33m\ \e[97;1;4mLost\e[0;97m? type: \e[1;4mtakemeback\e[0;97m           \e[33m|
\e[31m       /#######/    \########################\  \e[33m|\e[97mShow this help again: \e[1;4mshowbanner\e[0;97m \e[33m|
\e[31m      /#######/      \#############/\#########\ \e[33m+=================================+
\e[31m     /#######/        \###########/  \#########\
\e[31m    /#######/          \#########/    \#########\
\e[31m   /#######/            \#######/      \#########\
\e[31m  /#######/              \#####/        \#########\
\e[31m /#######/                \###/          \#########\
\e[31m/#######/                  \#/            \#########\
\e[31m--------                    -              ----------'
echo '\e[0m';


