#!/bin/bash
#The following is the smushed and ready to be echoed out "M" header with all of 
#the color information intact.
#this information will be edited along with the correct_flag/file information file and then
#i'll edit it with sed to make sure that this matches but for now. It's about making sure it
#works rather than making sure it's autochanging.

#NOTE: DUE TO THE USER NOT OWNING SOME OF THE FILES THEY CANNOT MOVE THEM THUS THEY HAVE TO
#WAIT UPTO 60S AFTER LOGGING IN BEFORE A CHRONJOB CAN BE KICKED OFF AND MOVE THE FILES FOR
#THEM IN THE FUTURE I'LL LIKELY WRITE A CUSTOM SCRIPT DAEMON WHICH'LL CHECK FOR THE FOLDER
#EVERY 5S SO THAT THEY CAN MORE QUICKLY GET TO THE FLAG BUT FOR NOW THIS WILL WORK.
permission=777
permission='-rwxrwxrwx'
size=1339
owner=1006
group=1006
GOALSTR0=$( printf ' %s%13s' "permissions: $permission" '' );
GOALSTR1=$( printf '%37s' "size: $size owner: $owner group: $group" );
padding=$( printf $USER | wc -c );
padding=$(( 12 - $padding ));
user=$( printf "%s.%${padding}s" $USER '' );
#to make sure that the terminal's clear
#clear;
#to make sure that the logos will fit on the screen at one time with the user's 
#prompt. I also went over by three characters in the columns so I have to resize it
#for that also.
#to make sure it doesn't output pointless lines.
#resize -s 27 83 &>/dev/null;

#This is included to help me easily revert it to change the textbox later.
#I have ~362 characters to work with within it. It should be way more than enough
#for pretty much everything that I'll need to do as that's 80words. I'll create
#smaller versions of the textbox for earlier flags. Small box should be ~100 chars.

#color table: 31=red fg, 33=yellow fg, 97=white fg. 1=bold,4=underlined.
#remove later.
#old colored version
#current version.
#I start off by clearing all formatting so that I can be sure that it'll show up
#the way that I want. Then I go into using escape codes to colorize it to look
#way nicer. The text at the top will likely just be MECC.edu/Cyber or something
#similar.
echo '\e[0m\e[31m                        /#\
\e[31m                       /###\
\e[31m                      /#####\           \e[1m*****\e[1;4mWelcome to the Hunt @ MECC\e[0;1m****\e[0m
\e[31m                     /#######\
\e[31m                    /#########\           \e[33m+======================================+  
\e[31m                   /##########/           \e[33m|\e[97m You are on currently on '"$user"'\e[33m|
\e[31m                  /##########/  /\        \e[33m|\e[97m The goal this time is to find a file \e[33m|
\e[31m                 /##########/  /##\       \e[33m|\e[97m that has the following metadata;     \e[33m|
\e[31m                /##########/  /###/  _    \e[33m|\e[97m'"$GOALSTR0"' \e[33m|
\e[31m               /##########/__/###/  /#\   \e[33m|\e[97m'"$GOALSTR1"' \e[33m|
\e[31m              /#################/  /###\  \e[33m|\e[97m Some interesting commands to try     \e[33m|
\e[31m             /#################/  /#####\  \e[33m\ \e[97mcd, ls, cat, file, man, find        \e[33m|
\e[31m           /##################/__/#######\  \e[33m\ \e[97mIf \e[1;4myou\e[0;97m mess up: reset_ctf          \e[33m|
\e[31m          /###############################\ \e[33m \ \e[97mIf \e[1;4mit\e[0;97m messes up: blame -debug     \e[33m|
\e[31m         /#######/\########################\ \e[33m | \e[97;1;4mLost\e[0;97m? type: \e[1;4mtakemeback\e[0;97m           \e[33m|
\e[31m        /#######/  \########################\ \e[33m| \e[97mShow this help again: \e[1;4mshowbanner\e[0;97m \e[33m|
\e[31m       /#######/    \########################\ \e[33m+=================================+
\e[31m      /#######/      \#############/\#########\ \e[33;1m **Flag will be ready in 60s**\e[0m
\e[31m     /#######/        \###########/  \#########\
\e[31m    /#######/          \#########/    \#########\
\e[31m   /#######/            \#######/      \#########\
\e[31m  /#######/              \#####/        \#########\
\e[31m /#######/                \###/          \#########\
\e[31m/#######/                  \#/            \#########\
\e[31m--------                    -              ----------'
echo '\e[0m';
