#!/bin/bash
#The following is the smushed and ready to be echoed out "M" header with all of 
#the color information intact.
#HOUND='hound zero';
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
#to make sure that the terminal's clear
#clear;
#to make sure that the logos will fit on the screen at one time with the user's 
#prompt. I also went over by three characters in the columns so I have to resize it
#for that also.
#to make sure it doesn't output pointless lines.
#resize -s 27 83 &>/dev/null;

#This is included to help me easily revert it to change the textbox later.
#I have ~362 characters to work with within it. It should be way more than enough
#for pretty much everything that I'll need to do as that's 80words. I'll create
#smaller versions of the textbox for earlier flags. Small box should be ~100 chars.

#color table: 31=red fg, 33=yellow fg, 97=white fg. 1=bold,4=underlined.
padding=$( printf $USER | wc -c );
padding=$(( 12 - $padding ));
user=$( printf "%s.%${padding}s" $USER '' );
string='prattling                                '
#remove later.
#old colored version
#current version.
#I start off by clearing all formatting so that I can be sure that it'll show up
#the way that I want. Then I go into using escape codes to colorize it to look
#way nicer. The text at the top will likely just be MECC.edu/Cyber or something
#similar.
echo '\e[0m\e[31m                        /#\
\e[31m                       /###\
\e[31m                      /#####\
\e[31m                     /#######\
\e[31m                    /#########\
\e[31m                   /##########/              \e[1m*****\e[1;4mWelcome to the Hunt @ MECC\e[24m****\e[0m
\e[31m                  /##########/  /\      \e[33m+============================================+
\e[31m                 /##########/  /##\     \e[33m|\e[97m You are on currently on '"$user"'      \e[33m|
\e[31m                /##########/  /###/  _  \e[33m|\e[97mGoal:use strings on the file then pipe the  \e[33m|
\e[31m               /##########/__/###/  /#\  \e[33m\ \e[97moutput to grep, & match the following word\e[33m|
\e[31m              /#################/  /###\  \e[33m\ \e[97m'"$string"'\e[33m|
\e[31m             /#################/  /#####\  \e[33m\ \e[97m Commands: ls,\e[1;4mregexer\e[0;97m,regex_help        \e[33m|
\e[31m           /##################/__/#######\  \e[33m\ \e[97mIf \e[1;4myou\e[0;97m mess up: reset_ctf              \e[33m|
\e[31m          /###############################\  \e[33m\ \e[97mIf \e[1;4mit\e[0;97m messes up: blame -debug         \e[33m|
\e[31m         /#######/\########################\  \e[33m\ \e[97;1;4mLost\e[0;97m? type: \e[1;4mtakemeback\e[0;97m               \e[33m|
\e[31m        /#######/  \########################\  \e[33m\ \e[97mShow this help again: \e[1;4mshowbanner\e[0;97m    \e[33m|
\e[31m       /#######/    \########################\  \e[33m+====================================+
\e[31m      /#######/      \#############/\#########\
\e[31m     /#######/        \###########/  \#########\
\e[31m    /#######/          \#########/    \#########\
\e[31m   /#######/            \#######/      \#########\
\e[31m  /#######/              \#####/        \#########\
\e[31m /#######/                \###/          \#########\
\e[31m/#######/                  \#/            \#########\
\e[31m--------                    -              ----------'
echo '\e[0m';

