#!/bin/bash
#The following is the smushed and ready to be echoed out "M" header with all of
#the color information intact.
#HOUND='hound zero';
#GOALSTR='Use regex to find the flag!';
#to make sure that the terminal's clear
#clear;
#to make sure that the logos will fit on the screen at one time with the user's
#prompt. I also went over by three characters in the columns so I have to resize it
#for that also.
#to make sure it doesn't output pointless lines.
#resize -s 27 83 &>/dev/null;

#This is included to help me easily revert it to change the textbox later.
#I have ~362 characters to work with within it. It should be way more than enough
#for pretty much everything that I'll need to do as that's 80words. I'll create
#smaller versions of the textbox for earlier flags. Small box should be ~100 chars.

#color table: 31=red fg, 33=yellow fg, 97=white fg. 1=bold,4=underlined.
padding=$( printf $USER | wc -c );
padding=$(( 12 - $padding ));
user=$( printf "%s.%${padding}s" $USER '' );
GOAL_STR0='The RegEx must match a string that ends    '
GOAL_STR1='with a number.                             '
LINE_LEN=64
#remove later.
#old colored version
#current version.
#I start off by clearing all formatting so that I can be sure that it'll show up
#the way that I want. Then I go into using escape codes to colorize it to look
#way nicer. The text at the top will likely just be MECC.edu/Cyber or something
#similar.
echo '\e[0m\e[31m                        /#\
\e[31m                       /###\
\e[31m                      /#####\
\e[31m                     /#######\
\e[31m                    /#########\        \e[1m*****\e[1;4mWelcome to the Hunt @ MECC\e[1m****\e[0m
\e[31m                   /##########/         \e[33m+==============================================+
\e[31m                  /##########/  /\      \e[33m|\e[97m You are on currently on '"$user"'        \e[33m|
\e[31m                 /##########/  /##\     \e[33m|\e[97m GOAL:Write an \e[1;4mawk\e[0;97m script to find the flag in \e[33m|
\e[31m                /##########/  /###/  _  \e[33m|\e[97m the file. It has a line length of \e[1;4m'$LINE_LEN'\e[0;97m and also\e[33m|
\e[31m               /##########/__/###/  /#\ \e[33m\ \e[97mmatches the regex pattern given to you below.\e[33m|
\e[31m              /#################/  /###\ \e[33m\ \e[97m'"$GOAL_STR0"' \e[33m|
\e[31m             /#################/  /#####\ \e[33m\ \e[97m'"$GOAL_STR1"'\e[33m|
\e[31m           /##################/__/#######\ \e[33m\ \e[97mCommands: ls,man,info,awk,nano,regex_help \e[33m|
\e[31m          /###############################\ \e[33m\ \e[97mIf \e[1;4myou\e[0;97m mess up: reset_ctf                \e[33m|
\e[31m         /#######/\########################\ \e[33m\ \e[97mIf \e[1;4mit\e[0;97m messes up: blame -debug           \e[33m|
\e[31m        /#######/  \########################\ \e[33m\ \e[97;1;4mLost\e[0;97m? type: \e[1;4mtakemeback\e[0;97m                 \e[33m|
\e[31m       /#######/    \########################\ \e[33m\ \e[97mShow this help again: \e[1;4mshowbanner\e[0;97m      \e[33m|
\e[31m      /#######/      \#############/\#########\ \e[33m+======================================+
\e[31m     /#######/        \###########/  \#########\
\e[31m    /#######/          \#########/    \#########\
\e[31m   /#######/            \#######/      \#########\
\e[31m  /#######/              \#####/        \#########\
\e[31m /#######/                \###/          \#########\
\e[31m/#######/                  \#/            \#########\
\e[31m--------                    -              ----------'
echo '\e[0m';
