#!/bin/bash
max_dir=10;
max_file=6;
correct_flag='';
correct_dir=$(( $RANDOM % $max_dir ));
correct_file=$(( $RANDOM % $max_file ));
dir_prefix='maybe';
file_prefix='file';
rm -rvf bunch_dirs;
mkdir bunch_dirs;
cd bunch_dirs;
name='';
for (( i=0; i<$max_dir; i++ )) do
    name=$i;
    if(( $i <=9 ))
    then
        name="0$i";
    fi
    mkdir "$dir_prefix$name"
done
