#!/bin/bash
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019- AGPLv3
MAX=15;
correct_flag=$(( $RANDOM % $MAX ));
rm -rvf ../hounds/hound5/.secret/*
rm -rvf bunch_dirs;
mkdir bunch_dirs;
cd bunch_dirs;
incorrect_flag_str='';
name='';
for (( i=0; i<=$MAX; i++))
do
name=$i;
if(( $i <=9 ))
then
    name="0$i";
fi
#    echo $RANDOM | openssl dgst -sha1 -binary > "-file$name";
#	incorrect_flag_str=$( echo $RANDOM | openssl dgst -sha256 -binary
	dd if=/dev/random bs=1 count=29 status=none > "-file$name";
    if [[ $i -eq $correct_flag ]]
    then
        echo '3h9GplLdLnj9e6uYVToiNMBLFcY=' > "-file$name";
    fi
done
echo 'done';
cd ..;
cp -Rv bunch_dirs/* ../hounds/hound4/.secrets;
rm -rv bunch_dirs;
