#!/bin/bash
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
if [ $# -ge 1 ];then
    case "$1" in
        -h)
            printf "pass the awk script you want to test as the only argument to this program.\n";
        ;;
        *)
            awk --source 'BEGIN { exit(0) } END { exit(0) }' --file "$1"; 
        ;;
    esac
else
    printf "pass the awk script you want to test as the only argument to this program.\n";
fi

