#!/bin/bash
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
DIRNAME=$(echo "$SSH_CONNECTION$USER" | openssl dgst -sha1 -binary | base64 | tr '+\/' '-_');
case $1 in
	'-debug')
	echo "Person to blame: Macarthur Inbody <admin_contact@transcendental.us> Debug info: d|$DIRNAME f|$USER name:$MEME_NAME";;
	'-person')
	echo "Person to blame: Macarthur Inbody <admin_contact@transcendental.us>";;
	*)
	echo -e 'usage: blame -person|-debug\n -person will say who to blame -debug will also help them figure out what went wrong.'
	;;
esac
