#!/bin/bash
#temporary
#Macarthur Inbody <mdi2455@email.vccs.edu> 2019- AGPLv3
DIRNAME=$(echo "$SSH_CONNECTION$USER" | openssl dgst -sha1 -binary | base64 | tr '+\/' '-_');
case $1 in
	'-debug')
	echo "Person to blame: Macarthur Inbody <mdi2455@email.vccs.edu> Debug info: d|$DIRNAME f|$HOUND";;
	'-person')
	echo "Person to blame: Macarhtur Inbody <mdi2455@email.vccs.edu>";;
	*)
	echo -e 'usage: blame -person|-debug\n -person will say who to blame -debug will also help them figure out what went wrong.'
	;;
esac
