#!/bin/bash
dirname=$(echo "$SSH_CONNECTION$USER" | openssl dgst -sha1 -binary | base64 | tr '+\/' '-_');
echo -e 'To get back to your directory go to\n /tmp/foxhunt/'"$dirname\n by typing\n cd /tmp/foxhunt/$dirname";
