#!/bin/bash
# Macarthur Inbody
# mdi2455@email.vccs.edu / admin-contact@transcendental.us
# Licenesed under AGPLv3
# (C) 2019 -
dirname=$(echo "$SSH_CONNECTION$USER" | openssl dgst -sha1 -binary | base64 | tr '+\/' '-_')
mkdir /tmp/foxhunt/"$dirname";
tar -xvJ /home/$USER/challenge_file.txz -C /tmp/foxhunt/"$dirname"
cd $dirname;

