#!/bin/sh
#oneline awk script to count the length of every line and then sort it into a nice pattern. So that I can get a distrubtion of character lengths.
#argument 1 is the file to search through. It gives a nice graph.
awk '{print length}' $1 | sort -g | uniq -c
